apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "web-app-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-app-svc.selectorLabels" . | nindent 6 }}
    strategy: {{- toYaml .Values.deploymentStrategy | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-app-svc.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}