apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: python 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: jasimdocker003/python-server:latest
        imagePullPolicy: IfNotPresent
        name: python
        resources: 
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python
  sessionAffinity: None
  type: ClusterIP
